name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: dotnet test
      
      - name: Publish
        run: dotnet publish WeatherApi/WeatherApi.csproj -c Release -o './publish'
        
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy
        uses: Azure/webapps-deploy@v2
        with:
          app-name: fv-weatherapi
          package: './publish'
