name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: zippy-weather-dev-rg
      ResourceGroupLocation: "Australia East"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: dotnet test -l --logger trx -r 'TestsReport/'
      
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Display Test Results
          path: '**/*.trx'
          reporter: dotnet-trx
      
