name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: zippy-weather-dev-rg
      ResourceGroupLocation: "Australia East"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Ensure Azure Resource Group Created
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/python3
            rg_exists = az group exists --name ${{ env.ResourceGroupName }} 
            if rg_exists:
              print('Rg exists already')
            else:
              print('Creating resource')
            
