name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: dotnet test
      
      - name: Publish
        run: dotnet publish WeatherApi/WeatherApi.csproj -c Release -o './publish'
        
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: b20ca6b2-60c6-48a9-8fe1-e3b9e159281a
          region: Australia East
          resourceGroupName: zippy-dev-rg
          template: Infrastructure/template.json
          deploymentMode: Complete
          parameters: hostingPlanName=ZippyWeatherDevAsp name=ZippyWeatherApiDevFv environment=Development
      
      - name: Deploy
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ZippyWeatherApiDevFv
          package: './publish'
