name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Test
        run: dotnet test
      
      - name: Publish
        run: dotnet publish WeatherApi/WeatherApi.csproj -c Release -o './publish'
        
      - name: Deploy Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: fv-weatherapi
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish'
